apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: food-deployment
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: food-deployment
  targetCPUUtilizationPercentage: 80
